export const db = [
    {
        id: 1,
        nombre: 'Lukather',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_01_lp2xyv.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 299,
    },
    {
        id: 2,
        nombre: 'SRV',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_02_hawhna.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 349,
    },
    {
        id: 3,
        nombre: 'Borland',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_03_oy7cov.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 329,
    },
    {
        id: 4,
        nombre: 'VAI',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_04_xbs2de.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 299,
    },
    {
        id: 5,
        nombre: 'Thompson',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_05_hyyhuz.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 399,
    },
    {
        id: 6,
        nombre: 'White',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_06_abpqvn.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 329,
    },
    {
        id: 7,
        nombre: 'Cobain',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_07_qihrr2.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 349,
    },
    {
        id: 8,
        nombre: 'Dale',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_08_zic5j9.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 379,
    },
    {
        id: 9,
        nombre: 'Krieger',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_09_epkrpt.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 289,
    },
    {
        id: 10,
        nombre: 'Campbell',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_10_ubpokn.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 349,
    },
    {
        id: 11,
        nombre: 'Reed',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_11_zwfhzb.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 399,
    },
    {
        id: 12,
        nombre: 'Hazel',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_12_g9pwgx.jpg',
        descripcion: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        precio: 379,
    },
]