export const db = [
    {
        id: 1,
        nombre: 'Lukather',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_01_lp2xyv.jpg',
        descripcion: ' Conocida por su cuerpo contorneado de aliso, tres pastillas y selector de cinco posiciones, ofrece versatilidad tonal y un diseño clásico que ha dejado su huella en la historia del rock.',
        precio: 299,
    },
    {
        id: 2,
        nombre: 'SRV',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_02_hawhna.jpg',
        descripcion: 'Con su cuerpo sólido y grueso, ofrece un sonido cálido y potente. Sus pastillas dobles humbucker proporcionan tonos ricos y cremosos, haciendo de esta guitarra una elección favorita en géneros como el rock y el blues.',
        precio: 349,
    },
    {
        id: 3,
        nombre: 'Borland',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_03_oy7cov.jpg',
        descripcion: 'Conocida por su diseño aerodinámico, mástil delgado y pastillas de alta ganancia, es ideal para los amantes del metal. Su construcción robusta y versatilidad tonal la convierten en una opción popular para guitarristas de alto rendimiento.',
        precio: 329,
    },
    {
        id: 4,
        nombre: 'VAI',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_04_xbs2de.jpg',
        descripcion: 'Combina la elegancia y la versatilidad. Con un cuerpo de caoba y tapa de arce, así como dos pastillas humbucker, ofrece tonos cálidos y nítidos, siendo una opción versátil para varios estilos musicales.',
        precio: 299,
    },
    {
        id: 5,
        nombre: 'Thompson',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_05_hyyhuz.jpg',
        descripcion: 'Es una guitarra semihueca con un sonido distintivo y brillante. Conocida por su asociación con los sonidos clásicos de los Beatles, es una elección popular para estilos que van desde el rock hasta el indie.',
        precio: 399,
    },
    {
        id: 6,
        nombre: 'White',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_06_abpqvn.jpg',
        descripcion: 'Diseñada para el shred, presenta un mástil rápido, cuerpo de aliso y pastillas de alta ganancia. Ideal para guitarristas que buscan velocidad y precisión en sus interpretaciones.',
        precio: 329,
    },
    {
        id: 7,
        nombre: 'Cobain',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_07_qihrr2.jpg',
        descripcion: 'Combina el estilo vintage con un sonido distintivo. Con sus pastillas Filter Tron, esta guitarra semihueca ofrece un tono claro y resonante, perfecto para estilos que van desde el rockabilly hasta el jazz.',
        precio: 349,
    },
    {
        id: 8,
        nombre: 'Dale',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_08_zic5j9.jpg',
        descripcion: 'Diseñada para el heavy metal, presenta un cuerpo de caoba y pastillas EMG activas. Con un mástil delgado y acceso sin restricciones a los trastes superiores, es una elección popular entre los guitarristas de metal moderno.',
        precio: 379,
    },
    {
        id: 9,
        nombre: 'Krieger',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_09_epkrpt.jpg',
        descripcion: 'Es conocida por su cuerpo delgado y liviano, ofreciendo un sonido brillante y agresivo. Ha sido una elección favorita para guitarristas de rock y metal desde la década de 1960.',
        precio: 289,
    },
    {
        id: 10,
        nombre: 'Campbell',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707653/img/guitarra_10_ubpokn.jpg',
        descripcion: 'Con pastillas activas EMG, es una guitarra diseñada para la potencia y la versatilidad en estilos de metal moderno. Su estética agresiva y sonido contundente la hacen destacar en el escenario.',
        precio: 349,
    },
    {
        id: 11,
        nombre: 'Reed',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_11_zwfhzb.jpg',
        descripcion: 'Es conocida por ser una guitarra versátil y asequible. Con un diseño clásico de doble cutaway, pastillas versátiles y construcción de calidad, es una opción popular para guitarristas principiantes y experimentados por igual.',
        precio: 399,
    },
    {
        id: 12,
        nombre: 'Hazel',
        imagen: 'https://res.cloudinary.com/dwrupo75d/image/upload/v1705707654/img/guitarra_12_g9pwgx.jpg',
        descripcion: 'Es una guitarra eléctrica icónica con un diseño distintivo en forma de V. Conocida por su apariencia llamativa y su sonido potente, ha sido utilizada en una variedad de géneros, desde el rock clásico hasta el heavy metal.',
        precio: 379,
    },
]